language: go

go:
  - 1.2
  - 1.3
  - 1.4
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/dgryski/go-jump
  - go get github.com/GaryBoone/GoStats/stats
script:
    - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN
